events { }

http {
    upstream app_get {
        server app-get:8080;
    }

    upstream app_post {
        server app-post:8080;
    }

    server {
        listen 80;

        # GET-запросы перенаправляются в app-get
        location / {
            if ($request_method = GET) {
                proxy_pass http://app_get;
                break;
            }

            # Остальные запросы перенаправляются в app-post
            proxy_pass http://app_post;
        }

        # Настройка прокси
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
